version: "3.9"

services:
  postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 3

  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  streamlit:
    build:
      context: ./streamlit
    volumes:
      - ./streamlit:/code
    ports:
      - "9000:9000"

volumes:
  app-db-data:
  root-home:
